version: '3'

services:
  red-tetris-front:
    build: ./front
    container_name: red-tetris-front
    restart: on-failure
    depends_on:
      - red-tetris-api
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
      - "24678:24678"
    command: "yarn dev"
  red-tetris-api:
    build: ./api
    container_name: red-tetris-api
    restart: on-failure
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
    command: "yarn start:dev"
